default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password:
  host: localhost

development:
  adapter: postgresql
  database: mynomster_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mynomster_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: postgres
  password: password
  database: mynomster_production
  pool: 5
  timeout: 5000
