development:
  adapter: postgresql
  encoding: utf8
  database: mynomster_development
  pool: 5
  timeout: 5000
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mynomster_test
  pool: 5
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: mynomster_production
  pool: 5
  password: password
